version: "3.9"
services:
  opcserver:
    build:
      context: ./opcserver
    ports:
      - "4840:4840"
  gateway:
    build:
      context: ./gateway
      args:
        OPC_UA_GATEWAY_VERSION: 1017.0.289
    environment:
      - baseUrl=https://TENANT_URL
      - tenantId=TENANT_ID
      - gatewayIdentifier=GATEWAY_IDENTIFIER_LINE1
      - gatewayName=Line1 Gateway
    volumes:
    - ./data/:/data
