version: "3.9"
services:
  opcserver:
    build:
      context: ./opcserver
    ports:
      - "4840:4840"
  gateway:
    build:
      context: ./gateway
      args:
        OPC_UA_GATEWAY_VERSION: 1015.0.278
    environment:
    - baseUrl=https://ck2.eu-latest.cumulocity.com/
    - tenantId=t306817378
    - gatewayIdentifier=GATEWAY_IDENTIFIER_LINE
    - gatewayName=Line1 Gateway
    volumes:
    - ./data/:/data
