version: "3.9"
services:
  opcserver:
    build:
      context: ./opcserver
    ports:
      - "4840:4840"
  gateway:
    build:
      context: ./gateway
    environment:
    - baseURL=https://TENANT_URL
    - tenantId=TENANT_ID
    - identifier=GATEWAY_IDENTIFIER
    volumes:
    - ./data/:/data
