C8Y:
    baseUrl: ${baseUrl}
gateway:
    bootstrap:
      tenantId: ${tenantId}
    identifier: ${gatewayIdentifier}
    name: ${gatewayName}
    db:
# The gateway uses the local database to store platform credentials and local cache. This parameter shows the location in which the local data should be stored.
        baseDir: ./data