### 1. Get Linux
FROM alpine:3.11

### 2. Get Java via the package manager
RUN apk update \
&& apk upgrade \
&& apk add --no-cache bash \
&& apk add --no-cache --virtual=build-dependencies unzip \
&& apk add --no-cache curl \
&& apk add --no-cache  openjdk11

## RUN wget http://resources.cumulocity.com/examples/opc-ua/opcua-device-gateway-1010.0.8.jar

####
#### OPTIONAL : 4. SET JAVA_HOME environment variable, uncomment the line below if you need it

#ENV JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"

####

ADD application-tenant.yaml /
ADD logging.xml /

# integrate opcua gateway
# alternative 1
ADD http://resources.cumulocity.com/examples/opc-ua/opcua-device-gateway-1010.0.8.jar /

# alternative 2
# alternatively run the following commands locally
# wget http://resources.cumulocity.com/examples/opc-ua/opcua-device-gateway-1010.0.8.jar
# and uncomment the following line ...
# ADD ./opcua-device-gateway-1010.0.8.jar /

CMD ["/usr/bin/java", "-Dlogging.config=file:./logging.xml", "-Dspring.profiles.active=default,tenant", "-jar", "opcua-device-gateway-1010.0.8.jar", "-Dspring.config.location=file:./application-tenant.yaml"]