### 1. Get Linux
FROM python:3.7

### 2. Install opcua
RUN pip install asyncua dataclasses
ENV TZ="Europe/Berlin"
### 3. Start server
EXPOSE 4840    
ADD server_generel.py /
CMD ["python3", "server_generel.py"]